version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - errorlint
  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true
  exclusions:
    paths:
      - internal/protos
      - tests/mocks
