// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: orchestrator_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskHubSidecarService_Hello_FullMethodName                                 = "/TaskHubSidecarService/Hello"
	TaskHubSidecarService_StartInstance_FullMethodName                         = "/TaskHubSidecarService/StartInstance"
	TaskHubSidecarService_GetInstance_FullMethodName                           = "/TaskHubSidecarService/GetInstance"
	TaskHubSidecarService_RewindInstance_FullMethodName                        = "/TaskHubSidecarService/RewindInstance"
	TaskHubSidecarService_RestartInstance_FullMethodName                       = "/TaskHubSidecarService/RestartInstance"
	TaskHubSidecarService_WaitForInstanceStart_FullMethodName                  = "/TaskHubSidecarService/WaitForInstanceStart"
	TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName             = "/TaskHubSidecarService/WaitForInstanceCompletion"
	TaskHubSidecarService_RaiseEvent_FullMethodName                            = "/TaskHubSidecarService/RaiseEvent"
	TaskHubSidecarService_TerminateInstance_FullMethodName                     = "/TaskHubSidecarService/TerminateInstance"
	TaskHubSidecarService_SuspendInstance_FullMethodName                       = "/TaskHubSidecarService/SuspendInstance"
	TaskHubSidecarService_ResumeInstance_FullMethodName                        = "/TaskHubSidecarService/ResumeInstance"
	TaskHubSidecarService_QueryInstances_FullMethodName                        = "/TaskHubSidecarService/QueryInstances"
	TaskHubSidecarService_ListInstanceIds_FullMethodName                       = "/TaskHubSidecarService/ListInstanceIds"
	TaskHubSidecarService_PurgeInstances_FullMethodName                        = "/TaskHubSidecarService/PurgeInstances"
	TaskHubSidecarService_GetWorkItems_FullMethodName                          = "/TaskHubSidecarService/GetWorkItems"
	TaskHubSidecarService_CompleteActivityTask_FullMethodName                  = "/TaskHubSidecarService/CompleteActivityTask"
	TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName              = "/TaskHubSidecarService/CompleteOrchestratorTask"
	TaskHubSidecarService_CompleteEntityTask_FullMethodName                    = "/TaskHubSidecarService/CompleteEntityTask"
	TaskHubSidecarService_StreamInstanceHistory_FullMethodName                 = "/TaskHubSidecarService/StreamInstanceHistory"
	TaskHubSidecarService_CreateTaskHub_FullMethodName                         = "/TaskHubSidecarService/CreateTaskHub"
	TaskHubSidecarService_DeleteTaskHub_FullMethodName                         = "/TaskHubSidecarService/DeleteTaskHub"
	TaskHubSidecarService_SignalEntity_FullMethodName                          = "/TaskHubSidecarService/SignalEntity"
	TaskHubSidecarService_GetEntity_FullMethodName                             = "/TaskHubSidecarService/GetEntity"
	TaskHubSidecarService_QueryEntities_FullMethodName                         = "/TaskHubSidecarService/QueryEntities"
	TaskHubSidecarService_CleanEntityStorage_FullMethodName                    = "/TaskHubSidecarService/CleanEntityStorage"
	TaskHubSidecarService_AbandonTaskActivityWorkItem_FullMethodName           = "/TaskHubSidecarService/AbandonTaskActivityWorkItem"
	TaskHubSidecarService_AbandonTaskOrchestratorWorkItem_FullMethodName       = "/TaskHubSidecarService/AbandonTaskOrchestratorWorkItem"
	TaskHubSidecarService_AbandonTaskEntityWorkItem_FullMethodName             = "/TaskHubSidecarService/AbandonTaskEntityWorkItem"
	TaskHubSidecarService_SkipGracefulOrchestrationTerminations_FullMethodName = "/TaskHubSidecarService/SkipGracefulOrchestrationTerminations"
)

// TaskHubSidecarServiceClient is the client API for TaskHubSidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskHubSidecarServiceClient interface {
	// Sends a hello request to the sidecar service.
	Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Starts a new orchestration instance.
	StartInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// Gets the status of an existing orchestration instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Rewinds an orchestration instance to last known good state and replays from there.
	RewindInstance(ctx context.Context, in *RewindInstanceRequest, opts ...grpc.CallOption) (*RewindInstanceResponse, error)
	// Restarts an orchestration instance.
	RestartInstance(ctx context.Context, in *RestartInstanceRequest, opts ...grpc.CallOption) (*RestartInstanceResponse, error)
	// Waits for an orchestration instance to reach a running or completion state.
	WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Waits for an orchestration instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Raises an event to a running orchestration instance.
	RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error)
	// Terminates a running orchestration instance.
	TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// Suspends a running orchestration instance.
	SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error)
	// Resumes a suspended orchestration instance.
	ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	QueryInstances(ctx context.Context, in *QueryInstancesRequest, opts ...grpc.CallOption) (*QueryInstancesResponse, error)
	ListInstanceIds(ctx context.Context, in *ListInstanceIdsRequest, opts ...grpc.CallOption) (*ListInstanceIdsResponse, error)
	PurgeInstances(ctx context.Context, in *PurgeInstancesRequest, opts ...grpc.CallOption) (*PurgeInstancesResponse, error)
	GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkItem], error)
	CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	CompleteOrchestratorTask(ctx context.Context, in *OrchestratorResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	CompleteEntityTask(ctx context.Context, in *EntityBatchResult, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	// Gets the history of an orchestration instance as a stream of events.
	StreamInstanceHistory(ctx context.Context, in *StreamInstanceHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoryChunk], error)
	// Deletes and Creates the necessary resources for the orchestration service and the instance store
	CreateTaskHub(ctx context.Context, in *CreateTaskHubRequest, opts ...grpc.CallOption) (*CreateTaskHubResponse, error)
	// Deletes the resources for the orchestration service and optionally the instance store
	DeleteTaskHub(ctx context.Context, in *DeleteTaskHubRequest, opts ...grpc.CallOption) (*DeleteTaskHubResponse, error)
	// sends a signal to an entity
	SignalEntity(ctx context.Context, in *SignalEntityRequest, opts ...grpc.CallOption) (*SignalEntityResponse, error)
	// get information about a specific entity
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// query entities
	QueryEntities(ctx context.Context, in *QueryEntitiesRequest, opts ...grpc.CallOption) (*QueryEntitiesResponse, error)
	// clean entity storage
	CleanEntityStorage(ctx context.Context, in *CleanEntityStorageRequest, opts ...grpc.CallOption) (*CleanEntityStorageResponse, error)
	// Abandons a single work item
	AbandonTaskActivityWorkItem(ctx context.Context, in *AbandonActivityTaskRequest, opts ...grpc.CallOption) (*AbandonActivityTaskResponse, error)
	// Abandon an orchestration work item
	AbandonTaskOrchestratorWorkItem(ctx context.Context, in *AbandonOrchestrationTaskRequest, opts ...grpc.CallOption) (*AbandonOrchestrationTaskResponse, error)
	// Abandon an entity work item
	AbandonTaskEntityWorkItem(ctx context.Context, in *AbandonEntityTaskRequest, opts ...grpc.CallOption) (*AbandonEntityTaskResponse, error)
	// "Skip" graceful termination of orchestrations by immediately changing their status in storage to "terminated".
	// Note that a maximum of 500 orchestrations can be terminated at a time using this method.
	SkipGracefulOrchestrationTerminations(ctx context.Context, in *SkipGracefulOrchestrationTerminationsRequest, opts ...grpc.CallOption) (*SkipGracefulOrchestrationTerminationsResponse, error)
}

type taskHubSidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskHubSidecarServiceClient(cc grpc.ClientConnInterface) TaskHubSidecarServiceClient {
	return &taskHubSidecarServiceClient{cc}
}

func (c *taskHubSidecarServiceClient) Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) StartInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) RewindInstance(ctx context.Context, in *RewindInstanceRequest, opts ...grpc.CallOption) (*RewindInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewindInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_RewindInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) RestartInstance(ctx context.Context, in *RestartInstanceRequest, opts ...grpc.CallOption) (*RestartInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_RestartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_WaitForInstanceStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaiseEventResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_RaiseEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_TerminateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_SuspendInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_ResumeInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) QueryInstances(ctx context.Context, in *QueryInstancesRequest, opts ...grpc.CallOption) (*QueryInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryInstancesResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_QueryInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) ListInstanceIds(ctx context.Context, in *ListInstanceIdsRequest, opts ...grpc.CallOption) (*ListInstanceIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstanceIdsResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_ListInstanceIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) PurgeInstances(ctx context.Context, in *PurgeInstancesRequest, opts ...grpc.CallOption) (*PurgeInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeInstancesResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_PurgeInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskHubSidecarService_ServiceDesc.Streams[0], TaskHubSidecarService_GetWorkItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetWorkItemsRequest, WorkItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskHubSidecarService_GetWorkItemsClient = grpc.ServerStreamingClient[WorkItem]

func (c *taskHubSidecarServiceClient) CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteActivityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) CompleteOrchestratorTask(ctx context.Context, in *OrchestratorResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) CompleteEntityTask(ctx context.Context, in *EntityBatchResult, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteEntityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) StreamInstanceHistory(ctx context.Context, in *StreamInstanceHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoryChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskHubSidecarService_ServiceDesc.Streams[1], TaskHubSidecarService_StreamInstanceHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInstanceHistoryRequest, HistoryChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskHubSidecarService_StreamInstanceHistoryClient = grpc.ServerStreamingClient[HistoryChunk]

func (c *taskHubSidecarServiceClient) CreateTaskHub(ctx context.Context, in *CreateTaskHubRequest, opts ...grpc.CallOption) (*CreateTaskHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskHubResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CreateTaskHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) DeleteTaskHub(ctx context.Context, in *DeleteTaskHubRequest, opts ...grpc.CallOption) (*DeleteTaskHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskHubResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_DeleteTaskHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) SignalEntity(ctx context.Context, in *SignalEntityRequest, opts ...grpc.CallOption) (*SignalEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalEntityResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_SignalEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) QueryEntities(ctx context.Context, in *QueryEntitiesRequest, opts ...grpc.CallOption) (*QueryEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEntitiesResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_QueryEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) CleanEntityStorage(ctx context.Context, in *CleanEntityStorageRequest, opts ...grpc.CallOption) (*CleanEntityStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanEntityStorageResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CleanEntityStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) AbandonTaskActivityWorkItem(ctx context.Context, in *AbandonActivityTaskRequest, opts ...grpc.CallOption) (*AbandonActivityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonActivityTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_AbandonTaskActivityWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) AbandonTaskOrchestratorWorkItem(ctx context.Context, in *AbandonOrchestrationTaskRequest, opts ...grpc.CallOption) (*AbandonOrchestrationTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonOrchestrationTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_AbandonTaskOrchestratorWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) AbandonTaskEntityWorkItem(ctx context.Context, in *AbandonEntityTaskRequest, opts ...grpc.CallOption) (*AbandonEntityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonEntityTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_AbandonTaskEntityWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) SkipGracefulOrchestrationTerminations(ctx context.Context, in *SkipGracefulOrchestrationTerminationsRequest, opts ...grpc.CallOption) (*SkipGracefulOrchestrationTerminationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkipGracefulOrchestrationTerminationsResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_SkipGracefulOrchestrationTerminations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskHubSidecarServiceServer is the server API for TaskHubSidecarService service.
// All implementations must embed UnimplementedTaskHubSidecarServiceServer
// for forward compatibility.
type TaskHubSidecarServiceServer interface {
	// Sends a hello request to the sidecar service.
	Hello(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Starts a new orchestration instance.
	StartInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// Gets the status of an existing orchestration instance.
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Rewinds an orchestration instance to last known good state and replays from there.
	RewindInstance(context.Context, *RewindInstanceRequest) (*RewindInstanceResponse, error)
	// Restarts an orchestration instance.
	RestartInstance(context.Context, *RestartInstanceRequest) (*RestartInstanceResponse, error)
	// Waits for an orchestration instance to reach a running or completion state.
	WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Waits for an orchestration instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Raises an event to a running orchestration instance.
	RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error)
	// Terminates a running orchestration instance.
	TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// Suspends a running orchestration instance.
	SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error)
	// Resumes a suspended orchestration instance.
	ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error)
	QueryInstances(context.Context, *QueryInstancesRequest) (*QueryInstancesResponse, error)
	ListInstanceIds(context.Context, *ListInstanceIdsRequest) (*ListInstanceIdsResponse, error)
	PurgeInstances(context.Context, *PurgeInstancesRequest) (*PurgeInstancesResponse, error)
	GetWorkItems(*GetWorkItemsRequest, grpc.ServerStreamingServer[WorkItem]) error
	CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error)
	CompleteOrchestratorTask(context.Context, *OrchestratorResponse) (*CompleteTaskResponse, error)
	CompleteEntityTask(context.Context, *EntityBatchResult) (*CompleteTaskResponse, error)
	// Gets the history of an orchestration instance as a stream of events.
	StreamInstanceHistory(*StreamInstanceHistoryRequest, grpc.ServerStreamingServer[HistoryChunk]) error
	// Deletes and Creates the necessary resources for the orchestration service and the instance store
	CreateTaskHub(context.Context, *CreateTaskHubRequest) (*CreateTaskHubResponse, error)
	// Deletes the resources for the orchestration service and optionally the instance store
	DeleteTaskHub(context.Context, *DeleteTaskHubRequest) (*DeleteTaskHubResponse, error)
	// sends a signal to an entity
	SignalEntity(context.Context, *SignalEntityRequest) (*SignalEntityResponse, error)
	// get information about a specific entity
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// query entities
	QueryEntities(context.Context, *QueryEntitiesRequest) (*QueryEntitiesResponse, error)
	// clean entity storage
	CleanEntityStorage(context.Context, *CleanEntityStorageRequest) (*CleanEntityStorageResponse, error)
	// Abandons a single work item
	AbandonTaskActivityWorkItem(context.Context, *AbandonActivityTaskRequest) (*AbandonActivityTaskResponse, error)
	// Abandon an orchestration work item
	AbandonTaskOrchestratorWorkItem(context.Context, *AbandonOrchestrationTaskRequest) (*AbandonOrchestrationTaskResponse, error)
	// Abandon an entity work item
	AbandonTaskEntityWorkItem(context.Context, *AbandonEntityTaskRequest) (*AbandonEntityTaskResponse, error)
	// "Skip" graceful termination of orchestrations by immediately changing their status in storage to "terminated".
	// Note that a maximum of 500 orchestrations can be terminated at a time using this method.
	SkipGracefulOrchestrationTerminations(context.Context, *SkipGracefulOrchestrationTerminationsRequest) (*SkipGracefulOrchestrationTerminationsResponse, error)
	mustEmbedUnimplementedTaskHubSidecarServiceServer()
}

// UnimplementedTaskHubSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskHubSidecarServiceServer struct{}

func (UnimplementedTaskHubSidecarServiceServer) Hello(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) StartInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) RewindInstance(context.Context, *RewindInstanceRequest) (*RewindInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RewindInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) RestartInstance(context.Context, *RestartInstanceRequest) (*RestartInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForInstanceStart not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForInstanceCompletion not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RaiseEvent not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) QueryInstances(context.Context, *QueryInstancesRequest) (*QueryInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryInstances not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) ListInstanceIds(context.Context, *ListInstanceIdsRequest) (*ListInstanceIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstanceIds not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) PurgeInstances(context.Context, *PurgeInstancesRequest) (*PurgeInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeInstances not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetWorkItems(*GetWorkItemsRequest, grpc.ServerStreamingServer[WorkItem]) error {
	return status.Error(codes.Unimplemented, "method GetWorkItems not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteActivityTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteOrchestratorTask(context.Context, *OrchestratorResponse) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOrchestratorTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteEntityTask(context.Context, *EntityBatchResult) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteEntityTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) StreamInstanceHistory(*StreamInstanceHistoryRequest, grpc.ServerStreamingServer[HistoryChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamInstanceHistory not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CreateTaskHub(context.Context, *CreateTaskHubRequest) (*CreateTaskHubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTaskHub not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) DeleteTaskHub(context.Context, *DeleteTaskHubRequest) (*DeleteTaskHubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskHub not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) SignalEntity(context.Context, *SignalEntityRequest) (*SignalEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalEntity not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) QueryEntities(context.Context, *QueryEntitiesRequest) (*QueryEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEntities not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CleanEntityStorage(context.Context, *CleanEntityStorageRequest) (*CleanEntityStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanEntityStorage not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) AbandonTaskActivityWorkItem(context.Context, *AbandonActivityTaskRequest) (*AbandonActivityTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonTaskActivityWorkItem not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) AbandonTaskOrchestratorWorkItem(context.Context, *AbandonOrchestrationTaskRequest) (*AbandonOrchestrationTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonTaskOrchestratorWorkItem not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) AbandonTaskEntityWorkItem(context.Context, *AbandonEntityTaskRequest) (*AbandonEntityTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonTaskEntityWorkItem not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) SkipGracefulOrchestrationTerminations(context.Context, *SkipGracefulOrchestrationTerminationsRequest) (*SkipGracefulOrchestrationTerminationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipGracefulOrchestrationTerminations not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) mustEmbedUnimplementedTaskHubSidecarServiceServer() {}
func (UnimplementedTaskHubSidecarServiceServer) testEmbeddedByValue()                               {}

// UnsafeTaskHubSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskHubSidecarServiceServer will
// result in compilation errors.
type UnsafeTaskHubSidecarServiceServer interface {
	mustEmbedUnimplementedTaskHubSidecarServiceServer()
}

func RegisterTaskHubSidecarServiceServer(s grpc.ServiceRegistrar, srv TaskHubSidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskHubSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskHubSidecarService_ServiceDesc, srv)
}

func _TaskHubSidecarService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).Hello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).StartInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_RewindInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewindInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).RewindInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_RewindInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).RewindInstance(ctx, req.(*RewindInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_RestartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).RestartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_RestartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).RestartInstance(ctx, req.(*RestartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_WaitForInstanceStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_WaitForInstanceStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceStart(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_WaitForInstanceCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceCompletion(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_RaiseEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaiseEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).RaiseEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_RaiseEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).RaiseEvent(ctx, req.(*RaiseEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_TerminateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).TerminateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_TerminateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).TerminateInstance(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_SuspendInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).SuspendInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_SuspendInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).SuspendInstance(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_ResumeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).ResumeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_ResumeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).ResumeInstance(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_QueryInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).QueryInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_QueryInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).QueryInstances(ctx, req.(*QueryInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_ListInstanceIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstanceIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).ListInstanceIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_ListInstanceIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).ListInstanceIds(ctx, req.(*ListInstanceIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_PurgeInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).PurgeInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_PurgeInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).PurgeInstances(ctx, req.(*PurgeInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetWorkItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorkItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskHubSidecarServiceServer).GetWorkItems(m, &grpc.GenericServerStream[GetWorkItemsRequest, WorkItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskHubSidecarService_GetWorkItemsServer = grpc.ServerStreamingServer[WorkItem]

func _TaskHubSidecarService_CompleteActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteActivityTask(ctx, req.(*ActivityResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_CompleteOrchestratorTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrchestratorResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteOrchestratorTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteOrchestratorTask(ctx, req.(*OrchestratorResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_CompleteEntityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityBatchResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteEntityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteEntityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteEntityTask(ctx, req.(*EntityBatchResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_StreamInstanceHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamInstanceHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskHubSidecarServiceServer).StreamInstanceHistory(m, &grpc.GenericServerStream[StreamInstanceHistoryRequest, HistoryChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskHubSidecarService_StreamInstanceHistoryServer = grpc.ServerStreamingServer[HistoryChunk]

func _TaskHubSidecarService_CreateTaskHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CreateTaskHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CreateTaskHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CreateTaskHub(ctx, req.(*CreateTaskHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_DeleteTaskHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).DeleteTaskHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_DeleteTaskHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).DeleteTaskHub(ctx, req.(*DeleteTaskHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_SignalEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).SignalEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_SignalEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).SignalEntity(ctx, req.(*SignalEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_QueryEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).QueryEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_QueryEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).QueryEntities(ctx, req.(*QueryEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_CleanEntityStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanEntityStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CleanEntityStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CleanEntityStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CleanEntityStorage(ctx, req.(*CleanEntityStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_AbandonTaskActivityWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskActivityWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_AbandonTaskActivityWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskActivityWorkItem(ctx, req.(*AbandonActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_AbandonTaskOrchestratorWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonOrchestrationTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskOrchestratorWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_AbandonTaskOrchestratorWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskOrchestratorWorkItem(ctx, req.(*AbandonOrchestrationTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_AbandonTaskEntityWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonEntityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskEntityWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_AbandonTaskEntityWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).AbandonTaskEntityWorkItem(ctx, req.(*AbandonEntityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_SkipGracefulOrchestrationTerminations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipGracefulOrchestrationTerminationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).SkipGracefulOrchestrationTerminations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_SkipGracefulOrchestrationTerminations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).SkipGracefulOrchestrationTerminations(ctx, req.(*SkipGracefulOrchestrationTerminationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskHubSidecarService_ServiceDesc is the grpc.ServiceDesc for TaskHubSidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskHubSidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskHubSidecarService",
	HandlerType: (*TaskHubSidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _TaskHubSidecarService_Hello_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _TaskHubSidecarService_StartInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _TaskHubSidecarService_GetInstance_Handler,
		},
		{
			MethodName: "RewindInstance",
			Handler:    _TaskHubSidecarService_RewindInstance_Handler,
		},
		{
			MethodName: "RestartInstance",
			Handler:    _TaskHubSidecarService_RestartInstance_Handler,
		},
		{
			MethodName: "WaitForInstanceStart",
			Handler:    _TaskHubSidecarService_WaitForInstanceStart_Handler,
		},
		{
			MethodName: "WaitForInstanceCompletion",
			Handler:    _TaskHubSidecarService_WaitForInstanceCompletion_Handler,
		},
		{
			MethodName: "RaiseEvent",
			Handler:    _TaskHubSidecarService_RaiseEvent_Handler,
		},
		{
			MethodName: "TerminateInstance",
			Handler:    _TaskHubSidecarService_TerminateInstance_Handler,
		},
		{
			MethodName: "SuspendInstance",
			Handler:    _TaskHubSidecarService_SuspendInstance_Handler,
		},
		{
			MethodName: "ResumeInstance",
			Handler:    _TaskHubSidecarService_ResumeInstance_Handler,
		},
		{
			MethodName: "QueryInstances",
			Handler:    _TaskHubSidecarService_QueryInstances_Handler,
		},
		{
			MethodName: "ListInstanceIds",
			Handler:    _TaskHubSidecarService_ListInstanceIds_Handler,
		},
		{
			MethodName: "PurgeInstances",
			Handler:    _TaskHubSidecarService_PurgeInstances_Handler,
		},
		{
			MethodName: "CompleteActivityTask",
			Handler:    _TaskHubSidecarService_CompleteActivityTask_Handler,
		},
		{
			MethodName: "CompleteOrchestratorTask",
			Handler:    _TaskHubSidecarService_CompleteOrchestratorTask_Handler,
		},
		{
			MethodName: "CompleteEntityTask",
			Handler:    _TaskHubSidecarService_CompleteEntityTask_Handler,
		},
		{
			MethodName: "CreateTaskHub",
			Handler:    _TaskHubSidecarService_CreateTaskHub_Handler,
		},
		{
			MethodName: "DeleteTaskHub",
			Handler:    _TaskHubSidecarService_DeleteTaskHub_Handler,
		},
		{
			MethodName: "SignalEntity",
			Handler:    _TaskHubSidecarService_SignalEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _TaskHubSidecarService_GetEntity_Handler,
		},
		{
			MethodName: "QueryEntities",
			Handler:    _TaskHubSidecarService_QueryEntities_Handler,
		},
		{
			MethodName: "CleanEntityStorage",
			Handler:    _TaskHubSidecarService_CleanEntityStorage_Handler,
		},
		{
			MethodName: "AbandonTaskActivityWorkItem",
			Handler:    _TaskHubSidecarService_AbandonTaskActivityWorkItem_Handler,
		},
		{
			MethodName: "AbandonTaskOrchestratorWorkItem",
			Handler:    _TaskHubSidecarService_AbandonTaskOrchestratorWorkItem_Handler,
		},
		{
			MethodName: "AbandonTaskEntityWorkItem",
			Handler:    _TaskHubSidecarService_AbandonTaskEntityWorkItem_Handler,
		},
		{
			MethodName: "SkipGracefulOrchestrationTerminations",
			Handler:    _TaskHubSidecarService_SkipGracefulOrchestrationTerminations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWorkItems",
			Handler:       _TaskHubSidecarService_GetWorkItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamInstanceHistory",
			Handler:       _TaskHubSidecarService_StreamInstanceHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator_service.proto",
}
